-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.7.26 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for matcha
CREATE DATABASE IF NOT EXISTS `matcha` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `matcha`;

-- Dumping structure for table matcha.family_name_list
CREATE TABLE IF NOT EXISTS `family_name_list` (
  `name` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Dumping data for table matcha.family_name_list: 201 rows
/*!40000 ALTER TABLE `family_name_list` DISABLE KEYS */;
INSERT INTO `family_name_list` (`name`) VALUES
	('Martin'),
	('Bernard'),
	('Thomas'),
	('Petit'),
	('Robert'),
	('Richard'),
	('Durand'),
	('Dubois'),
	('Moreau'),
	('Laurent'),
	('Simon'),
	('Michel'),
	('Lefèvre'),
	('Leroy'),
	('Roux'),
	('David'),
	('Bertrand'),
	('Morel'),
	('Fournier'),
	('Girard'),
	('Bonnet'),
	('Dupont'),
	('Lambert'),
	('Fontaine'),
	('Rousseau'),
	('Vincent'),
	('Muller'),
	('Lefevre'),
	('Faure'),
	('Andre'),
	('Mercier'),
	('Blanc'),
	('Guerin'),
	('Boyer'),
	('Garnier'),
	('Chevalier'),
	('Francois'),
	('Legrand'),
	('Gauthier'),
	('Garcia'),
	('Perrin'),
	('Robin'),
	('Clement'),
	('Morin'),
	('Nicolas'),
	('Henry'),
	('Roussel'),
	('Mathieu'),
	('Gautier'),
	('Masson'),
	('Marchand'),
	('Duval'),
	('Denis'),
	('Dumont'),
	('Marie'),
	('Lemaire'),
	('Noel'),
	('Meyer'),
	('Dufour'),
	('Meunier'),
	('Brun'),
	('Blanchard'),
	('Giraud'),
	('Joly'),
	('Riviere'),
	('Lucas'),
	('Brunet'),
	('Gaillard'),
	('Barbier'),
	('Arnaud'),
	('Martinez'),
	('Gerard'),
	('Roche'),
	('Renard'),
	('Schmitt'),
	('Roy'),
	('Leroux'),
	('Colin'),
	('Vidal'),
	('Caron'),
	('Picard'),
	('Roger'),
	('Fabre'),
	('Aubert'),
	('Lemoine'),
	('Renaud'),
	('Dumas'),
	('Lacroix'),
	('Olivier'),
	('Philippe'),
	('Bourgeois'),
	('Pierre'),
	('Benoit'),
	('Rey'),
	('Leclerc'),
	('Payet'),
	('Rolland'),
	('Leclercq'),
	('Guillaume'),
	('Lecomte'),
	('Lopez'),
	('Jean'),
	('Dupuy'),
	('Guillot'),
	('Hubert'),
	('Berger'),
	('Carpentier'),
	('Sanchez'),
	('Dupuis'),
	('Moulin'),
	('Louis'),
	('Deschamps'),
	('Huet'),
	('Vasseur'),
	('Perez'),
	('Boucher'),
	('Fleury'),
	('Royer'),
	('Klein'),
	('Jacquet'),
	('Adam'),
	('Paris'),
	('Poirier'),
	('Marty'),
	('Aubry'),
	('Guyot'),
	('Carre'),
	('Charles'),
	('Renault'),
	('Charpentier'),
	('Menard'),
	('Maillard'),
	('Baron'),
	('Bertin'),
	('Bailly'),
	('Herve'),
	('Schneider'),
	('Fernandez'),
	('Le Gall'),
	('Collet'),
	('Leger'),
	('Bouvier'),
	('Julien'),
	('Prevost'),
	('Millet'),
	('Perrot'),
	('Daniel'),
	('Le Roux'),
	('Cousin'),
	('Germain'),
	('Breton'),
	('Besson'),
	('Langlois'),
	('Remy'),
	('Le Goff'),
	('Pelletier'),
	('Leveque'),
	('Perrier'),
	('Leblanc'),
	('Barre'),
	('Lebrun'),
	('Marchal'),
	('Weber'),
	('Mallet'),
	('Hamon'),
	('Boulanger'),
	('Jacob'),
	('Monnier'),
	('Michaud'),
	('Rodriguez'),
	('Guichard'),
	('Gillet'),
	('Etienne'),
	('Grondin'),
	('Poulain'),
	('Tessier'),
	('Chevallier'),
	('Collin'),
	('Chauvin'),
	('Da Silva'),
	('Bouchet'),
	('Gay'),
	('Lemaitre'),
	('Benard'),
	('Marechal'),
	('Humbert'),
	('Reynaud'),
	('Antoine'),
	('Hoarau'),
	('Perret'),
	('Barthelemy'),
	('Cordier'),
	('Pichon'),
	('Lejeune'),
	('Gilbert'),
	('Lamy'),
	('Delaunay'),
	('Pasquier'),
	('Carlier'),
	('Laporte'),
	('Whitman');
/*!40000 ALTER TABLE `family_name_list` ENABLE KEYS */;

-- Dumping structure for table matcha.first_name_list
CREATE TABLE IF NOT EXISTS `first_name_list` (
  `gender` varchar(50) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Dumping data for table matcha.first_name_list: 198 rows
/*!40000 ALTER TABLE `first_name_list` DISABLE KEYS */;
INSERT INTO `first_name_list` (`gender`, `name`) VALUES
	('m', 'Jean'),
	('f', 'Marie'),
	('m', 'Pierre'),
	('f', 'Jeanne'),
	('m', 'Michel'),
	('f', 'Françoise'),
	('m', 'André'),
	('f', 'Monique'),
	('m', 'Philippe'),
	('f', 'Catherine'),
	('m', 'René'),
	('f', 'Nathalie'),
	('m', 'Louis'),
	('f', 'Isabelle'),
	('m', 'Alain'),
	('f', 'Jacqueline'),
	('m', 'Jacques'),
	('f', 'Anne'),
	('m', 'Bernard'),
	('f', 'Sylvie'),
	('m', 'Marcel'),
	('f', 'Martine'),
	('m', 'Daniel'),
	('f', 'Madeleine'),
	('m', 'Roger'),
	('f', 'Nicole'),
	('m', 'Robert'),
	('f', 'Suzanne'),
	('m', 'Paul'),
	('f', 'Hélène'),
	('m', 'Claude'),
	('f', 'Christine'),
	('m', 'Christian'),
	('f', 'Marguerite'),
	('m', 'Henri'),
	('f', 'Denise'),
	('m', 'Georges'),
	('f', 'Louise'),
	('m', 'Nicolas'),
	('f', 'Christiane'),
	('m', 'François'),
	('f', 'Yvonne'),
	('m', 'Patrick'),
	('f', 'Valérie'),
	('m', 'Gérard'),
	('f', 'Sophie'),
	('m', 'Christophe'),
	('f', 'Sandrine'),
	('m', 'Joseph'),
	('f', 'Stéphanie'),
	('m', 'Julien'),
	('f', 'Céline'),
	('m', 'Maurice'),
	('f', 'Véronique'),
	('m', 'Laurent'),
	('f', 'Chantal'),
	('m', 'Frédéric'),
	('f', 'Marcelle'),
	('m', 'Eric'),
	('f', 'Renée'),
	('m', 'David'),
	('f', 'Simone'),
	('m', 'Stéphane'),
	('f', 'Jeannine'),
	('m', 'Pascal'),
	('f', 'Andrée'),
	('m', 'Sébastien'),
	('f', 'Julie'),
	('m', 'Alexandre'),
	('f', 'Paulette'),
	('m', 'Thierry'),
	('f', 'Germaine'),
	('m', 'Olivier'),
	('f', 'Annie'),
	('m', 'Thomas'),
	('f', 'Patricia'),
	('m', 'Antoine'),
	('f', 'Yvette'),
	('m', 'Raymond'),
	('f', 'Brigitte'),
	('m', 'Guy'),
	('f', 'Lucie'),
	('m', 'Dominique'),
	('f', 'Camille'),
	('m', 'Charles'),
	('f', 'Léa'),
	('m', 'Didier'),
	('f', 'Odette'),
	('m', 'Marc'),
	('f', 'Emilie'),
	('m', 'Vincent'),
	('f', 'Alice'),
	('m', 'Yves'),
	('f', 'Geneviève'),
	('m', 'Guillaume'),
	('f', 'Aurélie'),
	('m', 'Bruno'),
	('f', 'Laurence'),
	('m', 'Serge'),
	('f', 'Michèle'),
	('m', 'Maxime'),
	('f', 'Cécile'),
	('m', 'Lucien'),
	('f', 'Thérèse'),
	('m', 'Jean-Pierre'),
	('f', 'Colette'),
	('m', 'Albert'),
	('f', 'Virginie'),
	('m', 'Romain'),
	('f', 'Lucienne'),
	('m', 'Jerome'),
	('f', 'Dominique'),
	('m', 'Gilbert'),
	('f', 'Sarah'),
	('m', 'Franck'),
	('f', 'Raymonde'),
	('m', 'Gilles'),
	('f', 'Manon'),
	('m', 'Gabriel'),
	('f', 'Corinne'),
	('m', 'Anthony'),
	('f', 'Elisabeth'),
	('m', 'Jean-Claude'),
	('f', 'Juliette'),
	('m', 'Clément'),
	('f', 'Claire'),
	('m', 'Francis'),
	('f', 'Claudine'),
	('m', 'Emile'),
	('f', 'Danielle'),
	('m', 'Lucas'),
	('f', 'Elodie'),
	('m', 'Denis'),
	('f', 'Caroline'),
	('m', 'Kevin'),
	('f', 'Pauline'),
	('m', 'Mathieu'),
	('f', 'Christelle'),
	('m', 'Jules'),
	('f', 'Josette'),
	('m', 'Benjamin'),
	('f', 'Georgette'),
	('m', 'Alexis'),
	('f', 'Emma'),
	('m', 'Joël'),
	('f', 'Florence'),
	('m', 'Hervé'),
	('f', 'Laura'),
	('m', 'Patrice'),
	('f', 'Charlotte'),
	('m', 'Sylvain'),
	('f', 'Chloé'),
	('m', 'Hugo'),
	('f', 'Bernadette'),
	('m', 'Emmanuel'),
	('f', 'Mathilde'),
	('m', 'Adrien'),
	('f', 'Audrey'),
	('m', 'Fabrice'),
	('f', 'Maria'),
	('m', 'Arnaud'),
	('f', 'Gisèle'),
	('m', 'Cedric'),
	('f', 'Mélanie'),
	('m', 'Roland'),
	('f', 'Laetitia'),
	('m', 'Raphaël'),
	('f', 'Ginette'),
	('m', 'Florian'),
	('f', 'Annick'),
	('m', 'Quentin'),
	('f', 'Nadine'),
	('m', 'Ludovic'),
	('f', 'Béatrice'),
	('m', 'Damien'),
	('f', 'Mireille'),
	('m', 'Benoît'),
	('f', 'Anaïs'),
	('m', 'Victor'),
	('f', 'Evelyne'),
	('m', 'Fernand'),
	('f', 'Delphine'),
	('m', 'Léon'),
	('f', 'Henriette'),
	('m', 'Jeremy'),
	('f', 'Marion'),
	('m', 'Jean-Luc'),
	('f', 'Josiane'),
	('m', 'Arthur'),
	('f', 'Marthe'),
	('m', 'Théo'),
	('f', 'Michelle'),
	('m', 'Xavier'),
	('f', 'Karine'),
	('m', 'Fabien'),
	('f', 'Marine'),
	('m', 'Enzo'),
	('f', 'Elise');
/*!40000 ALTER TABLE `first_name_list` ENABLE KEYS */;

-- Dumping structure for table matcha.notif_likes
CREATE TABLE IF NOT EXISTS `notif_likes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dateadded` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `from_user` int(11) NOT NULL DEFAULT '0',
  `to_user` int(11) NOT NULL DEFAULT '0',
  `seen` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

-- Dumping data for table matcha.notif_likes: 0 rows
/*!40000 ALTER TABLE `notif_likes` DISABLE KEYS */;
/*!40000 ALTER TABLE `notif_likes` ENABLE KEYS */;

-- Dumping structure for table matcha.notif_matches
CREATE TABLE IF NOT EXISTS `notif_matches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dateadded` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `from_user` int(11) NOT NULL DEFAULT '0',
  `to_user` int(11) NOT NULL DEFAULT '0',
  `seen` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

-- Dumping data for table matcha.notif_matches: 0 rows
/*!40000 ALTER TABLE `notif_matches` DISABLE KEYS */;
/*!40000 ALTER TABLE `notif_matches` ENABLE KEYS */;

-- Dumping structure for table matcha.notif_profile_views
CREATE TABLE IF NOT EXISTS `notif_profile_views` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dateadded` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `from_user` int(11) NOT NULL DEFAULT '0',
  `to_user` int(11) NOT NULL DEFAULT '0',
  `seen` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Dumping data for table matcha.notif_profile_views: 2 rows
/*!40000 ALTER TABLE `notif_profile_views` DISABLE KEYS */;
/*!40000 ALTER TABLE `notif_profile_views` ENABLE KEYS */;

-- Dumping structure for table matcha.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(50) NOT NULL DEFAULT '0',
  `username` varchar(50) NOT NULL DEFAULT '0',
  `first_name` varchar(50) NOT NULL DEFAULT '0',
  `last_name` varchar(50) NOT NULL DEFAULT '0',
  `gender` varchar(50) NOT NULL DEFAULT '0',
  `password` varchar(200) NOT NULL DEFAULT '0',
  `sexual_orientation` varchar(50) NOT NULL DEFAULT '0',
  `bio` tinytext,
  `interests` tinytext,
  `image1` text,
  `image2` text,
  `image3` text,
  `image4` text,
  `mail_url` varchar(200) DEFAULT NULL,
  `password_recovery_url` varchar(200) DEFAULT NULL,
  `verified` tinyint(4) DEFAULT '0',
  `filter_age_min` int(11) DEFAULT '18',
  `filter_age_max` int(11) DEFAULT '100',
  `filter_distance_km` int(11) DEFAULT '20',
  `image5` text,
  `profile_image` tinyint(4) NOT NULL DEFAULT '-1',
  `age` int(11) DEFAULT '-1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- Dumping data for table matcha.users: 1 rows
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `email`, `username`, `first_name`, `last_name`, `gender`, `password`, `sexual_orientation`, `bio`, `interests`, `image1`, `image2`, `image3`, `image4`, `mail_url`, `password_recovery_url`, `verified`, `filter_age_min`, `filter_age_max`, `filter_distance_km`, `image5`, `profile_image`, `age`) VALUES
	(6, 'virgile.desvaux@gmail.com', 'zwokaros', 'Desvaux', 'Virgile', '0', '$2y$10$iFbKHtCSDqm0Ikix69g9dO4tgwN2nU7hptih6XJzB57Hc9YsLhPtS', '0', NULL, NULL, NULL, NULL, NULL, NULL, '', '', 1, 18, 100, 20, NULL, -1, -1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
